### ISSUE TITLE
Website is not mobile-friendly

### ISSUE THREAD

**Issue by Hywan** [fruux/sabre.io#28]

**Comment by Hywan** [comment]
After some work (I don't have the commit references), it's much better.

Thanks @demkani?

![screen shot 2015-01-06 at 11 49 33](https://cloud.githubusercontent.com/assets/946104/5627561/288c2542-959a-11e4-90c9-d030705be089.png)

The menu is still not perfect however.

**Comment by evert** [comment]
Hm.. did anyone change anything? Still needs a lot of work imho :) Try opening the docs

**Comment by demkani** [comment]
I wasn't since a while on it … At the moment i'm working on some scribbles ;)

**Comment by DominikTo** [comment]
Fixed with #31 and #32.
