### ISSUE TITLE
dav/clients/windows additions for HTTPS/SSL

### ISSUE THREAD

**Issue by RealRancor** [fruux/sabre.io#34]
Hi,

quoting from an older ownCloud forums thread (https://forum.owncloud.org/viewtopic.php?f=23&t=11246&p=61241#p61202) which maybe could also be added to http://sabre.io/dav/clients/windows/

> Worth noting for anyone who's still having this problem after making the registry change to enable Basic authentication is that the WebDAV implementation in Windows 7 and 8 requires a "poor" configuration of SSL on the server side - the WinHTTP API can only use an SSLv2 Hello message, and will only negotiate up to TLSv1.0. So if you've been following current security trends and restricted your HTTPS server to TLSv1.1 and above (which is a "good thing" as a rule) then the Windows WebDAV client will give you issues including the 1244 Error.

**Comment by Hywan** [comment]
@RealRancor Why not. Would you like to make a PR?

**Comment by RealRancor** [comment]
Hi,

merge request is done. I can't confirm this behavior but both linked infos in the PR is telling the same.
