### ISSUE TITLE
Poor anti-aliasing on firefox

### ISSUE THREAD

**Issue by evert** [fruux/sabre.io#51]
FF version 38.0.5.

![screenshot 2015-05-27 19 04 24](https://cloud.githubusercontent.com/assets/178960/7849426/4ccd3bb2-04a3-11e5-999a-bb06d7e40dad.png)

**Comment by staabm** [comment]
looks good on FF40.0a2 Win7-x64

**Comment by Hywan** [comment]
Version 85, w00t. Everything looks good with FF 40a2 (on Mac OS X).

**Comment by staabm** [comment]
seems like we are talking to a future-me of @evert ;)

**Comment by evert** [comment]
Meant version 38 ;)
