### ISSUE TITLE
No nav on ipad

### ISSUE THREAD

**Issue by staabm** [fruux/sabre.io#55]
It seems the css breakpoints are not properly configured to render a chapter-nav on landscape ipad viewport.

See http://m.imgur.com/krbWc1p

**Comment by staabm** [comment]
In portrait mode I get a "hamburger-menu" in the top left corner

**Comment by evert** [comment]
This is really weird... I don't fully understand why. The breakpoints seem fine on my computer

**Comment by staabm** [comment]
I dont know the reason yet, but I just reproduced it. Still an issue.

**Comment by staabm** [comment]
@evert was this change already published? Atm the issue is still reproducible

**Comment by evert** [comment]
@staabm can you do a hard refresh and try again?

**Comment by staabm** [comment]
How to do a hard refresh on ipad? :)

**Comment by evert** [comment]
Maybe @demkani can tell if I did it right?

**Comment by demkani** [comment]
Yup. Look OK for me. Checked it again and it's working on a "real" iPad 2 and some random Xcode simulators… @staabm If the issue still appears, can you give me some more details (iPad & iOS version…)?

**Comment by staabm** [comment]
@demkani I can still reproduce the issue on ipad air, ios9.2

STR
- goto http://sabre.io/xml/
- the top left should contain a hamburger menu, but it doesnt.

**Comment by staabm** [comment]
Seems fixed
