### ISSUE TITLE
VOBJECT hyperlink fail from http://sabre.io

### ISSUE THREAD

**Issue by B-Aerts** [fruux/sabre.io#60]
Hello,

couldn't reach the installation pages for VOBJECT at http://sabre.io/vobject/installation/.

Way to reproduce : 
- surf to http://sabre.io
- in ther line-up below, follow link "Sabre/vobject"
- on the Sabre/vobject page, follow ljnk "Installation"

Page returns 404 error and the request to file this under github .
Comments section remains visible

**Comment by Hywan** [comment]
Reproduced.

**Comment by staabm** [comment]
Fixed by https://github.com/fruux/sabre.io/commit/0bf549ab50ea159acb7d7366424b28ce3ed10df5
