### ISSUE TITLE
Wrong link to changelog in announcement blogposts

### ISSUE THREAD

**Issue by RealRancor** [fruux/sabre.io#80]
Hi,

hope this is the correct place to report that. Seems at http://sabre.io/blog/ some blogposts are referencing non-existing changelogs. I think its just a problem with Camelcase:

http://sabre.io/blog/2016/sabre-vobject-3.4.9-and-3.5.0-release
http://sabre.io/blog/2016/sabre-dav-2.1.8-released
http://sabre.io/blog/2015/sabre-dav-2.1.7-released

(Havn't checked older blogposts)

**Comment by evert** [comment]
Thank you! Fixed
