### ISSUE TITLE
Add a little information about character handling 

### ISSUE THREAD

**Issue by Mannshoch** [fruux/sabre.io#86]
> **Manipulating properties**
> 
> It's very easy to modify properties on objects:
> 
> ```
> // Overwrites or sets a property:
> $vcalendar->VEVENT->SUMMARY = 'Funeral';
> ```
// For special Characters like the var X-WR-CALNAME contains use following syntax
$vcalendar->{'X-WR-CALNAME'} = 'Title';
> ```
> 
> // Removes a property
> unset($vcalendar->VEVENT->DTSTAMP);
> 
> // Checks for existence of a property:
> isset($vcalendar->PRODID);
> 
> // Adds a property without overwriting an existing one.
> $vcalendar->VEVENT->add('ATTENDEE', 'mailto:foo@example.com');
> $vcalendar->VEVENT->add('ATTENDEE', 'mailto:evert@example.com');
> ```

**Comment by evert** [comment]
Thank you! For future reference every page in the github repository actually has an 'edit' button :) But I'm integrating this now.

**Comment by Mannshoch** [comment]
Sorry I never worked with that until now.
