### ISSUE TITLE
Convert Eugene's Baikal blog postings into a deployment HOWTO

### ISSUE THREAD

**Issue by pr3d4t0r** [fruux/sabre.io#93]
Convert Eugene's Baikal blog postings into a deployment HOWTO.

This is in response to conversations between pr3d4t0r and evrt regarding Ubuntu and Docker deployments.

**See**
https://ciurana.eu/entry/robust-calendar-service-deployment-howto
https://ciurana.eu/entry/improved-baikal-sabredav-calendar-in-less-than-10-minutes
https://groups.google.com/forum/#!topic/sabredav-discuss/iyAzOICttOM

**Comment by evert** [comment]
:+1: I like your idea of keeping the instructions as brief as possible and provide further detail on your blog. Looking forward to it!

**Comment by pr3d4t0r** [comment]
Branch:  **issue-93-Baikal-blog-to-HOWTO** from **master**.

Work started.

(I miss JIRA for the issue tracking part...)

**Comment by pr3d4t0r** [comment]
Hello, Evert!

The code/updates are almost ready for a pull request.  Before merging I have a few questions for you that need addressing:

1. The Makefile's first line says:  #!/bin/bash - typo?  May I remove it?
1. I found a few files with the +x flag set; PNG, the Makefile, others that usually don't require it -- may I set -x on them?
1. I found the https://hub.docker.com/fruux account -- could you please create a public or private repository for pushing the sabre.io image I made?  Please invite https://hub.docker.com/r/pr3d4t0r as a contributor to that account or repository

The answers to your questions will be used for:

1. Having a cleaner Makefile
1. Having a cleaner file system footprint
1. Defining the default `DOCKER_IMAGE=fruux/sabre.io` in the Makefile
1. Updating the Readme.md with the instructions on how to use/build the image and have it served from Docker Hub

You may preview the work I did at this [sabre.io hosted on ciurana.eu:8000](http://ciurana.eu:8000).  It was launched, built, etc. with only two commands:  `git clone` and `make docker_run`.  The whole thing was deployed and up-and-running in less than a minute.

If it makes things easier, let's chat on IRC; whatever works.

Cheers!

**Comment by evert** [comment]
> The Makefile's first line says: #!/bin/bash - typo? May I remove it?

Yes. Definitely wrong.

> I found a few files with the +x flag set; PNG, the Makefile, others that usually don't require it -- may I set -x on them?

Yep, totally

**Comment by pr3d4t0r** [comment]
Hi, Evert!

Did you have a chance to review the latest, leaner/meaner version?  How do we proceed?  Thanks and cheers!
